version: '3.9'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  python-app:
    build: .
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: python /app/db_conv.py

volumes:
  mongo-data:















